// Auto-generated by scripts/generate-post-index.mjs. Do not edit by hand.

export const generatedPosts = [
  {
    "slug": "AI-实践-vLLM模型加载失败排查记录_NVML_Unknown_Error",
    "sourcePath": "../content/posts/AI 实践/vLLM模型加载失败排查记录_NVML_Unknown_Error.md",
    "category": "AI 实践",
    "title": "vLLM 模型加载失败排查记录：Failed to infer device type 与 NVML Unknown Error",
    "date": "2026-07-17",
    "summary": "使用 vLLM 部署开源大模型时，Docker 容器无法初始化 NVML 导致启动失败的完整排查过程与解决方案。",
    "tags": [
      "AI 实践",
      "vLLM",
      "Docker",
      "GPU",
      "NVIDIA",
      "故障排查"
    ],
    "cover": "app-blue",
    "readingTime": "8 分钟",
    "featured": false
  },
  {
    "slug": "系统运维-terminal-multifunction-guide",
    "sourcePath": "../content/posts/系统运维/terminal-multifunction-guide.md",
    "category": "系统运维",
    "title": "打造一个多功能终端环境：基于 zsh、oh-my-zsh 与常用开发工具链",
    "date": "2026-06-25",
    "summary": "基于当前终端配置，梳理如何用 zsh、oh-my-zsh、自定义主题、插件补全、目录跳转和多语言工具链实现一个高效的多功能终端。",
    "tags": [
      "系统运维",
      "macOS",
      "zsh",
      "oh-my-zsh",
      "终端配置",
      "开发环境"
    ],
    "cover": "app-teal",
    "readingTime": "10 分钟",
    "featured": false
  },
  {
    "slug": "AI-实践-go-gin-mock-chat-server",
    "sourcePath": "../content/posts/AI 实践/go-gin-mock-chat-server.md",
    "category": "AI 实践",
    "title": "用 Go + Gin 搭一个本地 AI 流式响应 Mock 服务",
    "date": "2026-06-24",
    "summary": "为了让前端可以稳定复现各种 AI 聊天场景，用 Go + Gin 搭建了一个轻量本地 Mock 服务，模拟 OpenAI 风格和自定义协议的流式聊天接口。",
    "tags": [
      "AI 实践",
      "Go",
      "Gin",
      "Mock服务",
      "SSE",
      "流式响应",
      "前端调试",
      "AI接口"
    ],
    "cover": "app-teal",
    "readingTime": "10 分钟",
    "featured": false
  },
  {
    "slug": "功能测试-blog_agent_intent_detection",
    "sourcePath": "../content/posts/功能测试/blog_agent_intent_detection.md",
    "category": "功能测试",
    "title": "如何为 LLM Agent 安全检测构建 Mock 测试平台",
    "date": "2026-06-10",
    "summary": "介绍一套基于 Mock LLM + YAML 场景化用例 + Web 控制台的自动化测试方案，目前已沉淀 97 个测试用例，覆盖 11 个安全维度。",
    "tags": [
      "功能测试",
      "Mock测试",
      "LLM Agent",
      "安全检测",
      "自动化测试",
      "Django"
    ],
    "cover": "app-teal",
    "readingTime": "12 分钟",
    "featured": false
  },
  {
    "slug": "性能测试-BPS性能测试分享资料-BPS性能测试分享文章",
    "sourcePath": "../content/posts/性能测试/BPS性能测试分享资料/BPS性能测试分享文章.md",
    "category": "性能测试",
    "title": "使用 BPS 进行性能测试：并发、吞吐与新建连接",
    "date": "2026-06-03",
    "summary": "以 BPS 典型配置为例，梳理并发、吞吐和新建连接三类性能测试的目标、关键参数、Super Flow 设计、Load Profile 与结果观察重点。",
    "tags": [
      "性能测试",
      "BPS",
      "并发测试",
      "吞吐测试",
      "新建连接"
    ],
    "cover": "app-green",
    "readingTime": "25 分钟",
    "featured": false
  },
  {
    "slug": "系统运维-网卡带宽",
    "sourcePath": "../content/posts/系统运维/网卡带宽.md",
    "category": "系统运维",
    "title": "如何判断 40G 网卡的 PCIe 带宽是否足够",
    "date": "2026-05-29",
    "summary": "通过 lspci 查看 40G 网卡的 PCIe 链路速率和通道宽度，判断服务器是否具备跑满 40G 网络吞吐的硬件带宽。",
    "tags": [
      "系统运维",
      "Linux",
      "网卡",
      "PCIe"
    ],
    "cover": "app-orange",
    "readingTime": "5 分钟",
    "featured": false
  },
  {
    "slug": "AI-实践-壁仞上部署大模型",
    "sourcePath": "../content/posts/AI 实践/壁仞上部署大模型.md",
    "category": "AI 实践",
    "title": "在壁仞服务器上部署 Qwen3Guard-Gen-8B 与 bge-m3",
    "date": "2026-05-28",
    "summary": "记录在壁仞 8 卡服务器上使用 Docker 和 vLLM 部署 Qwen3Guard-Gen-8B 内容安全模型与 bge-m3 Embedding 模型，并通过 Nginx 暴露 OpenAI 兼容接口的实践过程。",
    "tags": [
      "AI 实践",
      "壁仞服务器",
      "大模型部署",
      "Qwen3Guard",
      "vLLM",
      "bge-m3"
    ],
    "cover": "app-teal",
    "readingTime": "12 分钟",
    "featured": true
  },
  {
    "slug": "AI-实践-海光上部署大模型",
    "sourcePath": "../content/posts/AI 实践/海光上部署大模型.md",
    "category": "AI 实践",
    "title": "在海光 DCU 服务器上部署 Qwen3Guard-Gen-8B、bge-m3 与 Qwen",
    "date": "2026-05-28",
    "summary": "记录在海光 DCU 环境中使用 Docker 和 vLLM 部署内容安全模型、Embedding 模型和通用大模型的实践，并整理日常巡检、接口验证和常见故障处理方法。",
    "tags": [
      "AI 实践",
      "海光DCU",
      "大模型部署",
      "Qwen3Guard",
      "vLLM",
      "bge-m3"
    ],
    "cover": "app-blue",
    "readingTime": "10 分钟",
    "featured": true
  },
  {
    "slug": "系统运维-Grafana_Prometheus",
    "sourcePath": "../content/posts/系统运维/Grafana_Prometheus.md",
    "category": "系统运维",
    "title": "Grafana + Prometheus 实战",
    "date": "2026-05-28",
    "summary": "Grafana + Prometheus 实战监控部署指南",
    "tags": [
      "系统运维",
      "Grafana",
      "Prometheus",
      "Linux"
    ],
    "cover": "app-orange",
    "readingTime": "8 分钟",
    "featured": false
  },
  {
    "slug": "AI-实践-skills_experience",
    "sourcePath": "../content/posts/AI 实践/skills_experience/分享.md",
    "category": "AI 实践",
    "title": "AI使用分享",
    "date": "2026-05-27",
    "summary": "分享 AI 辅助测试点、测试用例生成和 pytest 回放框架实现过程中的经验与注意事项。",
    "tags": [
      "AI 实践",
      "AI",
      "Skills",
      "测试工程",
      "大模型安全"
    ],
    "cover": "app-blue",
    "readingTime": "8 分钟",
    "featured": true
  },
  {
    "slug": "系统运维-modsecurity-about",
    "sourcePath": "../content/posts/系统运维/modsecurity-about.md",
    "category": "系统运维",
    "title": "什么是 ModSecurity",
    "date": "2026-05-23",
    "summary": "ModSecurity 是适用于 Apache、IIS 和 Nginx 的开源跨平台 Web 应用防火墙引擎。",
    "tags": [
      "系统运维",
      "ModSecurity",
      "WAF",
      "Web 安全防护"
    ],
    "cover": "app-green",
    "readingTime": "3 分钟",
    "featured": true
  },
  {
    "slug": "系统运维-ubuntu-tips",
    "sourcePath": "../content/posts/系统运维/ubuntu-tips.md",
    "category": "系统运维",
    "title": "Ubuntu 使用小技巧",
    "date": "2026-05-22",
    "summary": "迁移旧博客中 Ubuntu 使用过程中积累的小技巧，包括 vi 输入异常、root SSH 登录和 IP 配置。",
    "tags": [
      "系统运维",
      "Ubuntu",
      "Linux",
      "运维基础"
    ],
    "cover": "app-orange",
    "readingTime": "6 分钟",
    "featured": false
  },
  {
    "slug": "系统运维-ubuntu-x11vnc",
    "sourcePath": "../content/posts/系统运维/ubuntu-x11vnc.md",
    "category": "系统运维",
    "title": "Ubuntu 配置 x11VNC",
    "date": "2026-05-21",
    "summary": "迁移旧博客中 Ubuntu 安装、启动 x11VNC 并配置 systemd 自动启动的步骤。",
    "tags": [
      "系统运维",
      "Ubuntu",
      "x11VNC",
      "远程桌面"
    ],
    "cover": "app-pink",
    "readingTime": "6 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-CRLF-injection-CRLF注入详解与防护",
    "sourcePath": "../content/posts/安全研究/CRLF injection/CRLF注入详解与防护.md",
    "category": "安全研究",
    "title": "CRLF 注入详解与防护实践",
    "date": "2026-05-19",
    "summary": "系统梳理CRLF 注入的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "CRLF",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-teal",
    "readingTime": "14 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-CSRF-CSRF详解与防护",
    "sourcePath": "../content/posts/安全研究/CSRF/CSRF详解与防护.md",
    "category": "安全研究",
    "title": "CSRF 漏洞详解与防护实践",
    "date": "2026-05-18",
    "summary": "系统梳理CSRF的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "CSRF",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-blue",
    "readingTime": "14 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-Directory-listing-目录列表漏洞详解与防护",
    "sourcePath": "../content/posts/安全研究/Directory listing/目录列表漏洞详解与防护.md",
    "category": "安全研究",
    "title": "目录列表漏洞详解与防护实践",
    "date": "2026-05-17",
    "summary": "系统梳理目录列表漏洞的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "目录安全",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-yellow",
    "readingTime": "12 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-Directory_traversal-目录遍历漏洞详解与防护",
    "sourcePath": "../content/posts/安全研究/Directory_traversal/目录遍历漏洞详解与防护.md",
    "category": "安全研究",
    "title": "目录遍历漏洞详解与防护实践",
    "date": "2026-05-16",
    "summary": "系统梳理目录遍历的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "目录安全",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-green",
    "readingTime": "15 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-Email-injection-Email注入详解与防护",
    "sourcePath": "../content/posts/安全研究/Email injection/Email注入详解与防护.md",
    "category": "安全研究",
    "title": "Email 注入详解与防护实践",
    "date": "2026-05-15",
    "summary": "系统梳理Email 注入的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "Email注入",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-orange",
    "readingTime": "13 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-HTML-injection-HTML注入详解与防护",
    "sourcePath": "../content/posts/安全研究/HTML injection/HTML注入详解与防护.md",
    "category": "安全研究",
    "title": "HTML 注入详解与防护实践",
    "date": "2026-05-14",
    "summary": "系统梳理HTML 注入的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "HTML注入",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-pink",
    "readingTime": "14 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-IDOR-IDOR漏洞详解与防护",
    "sourcePath": "../content/posts/安全研究/IDOR/IDOR漏洞详解与防护.md",
    "category": "安全研究",
    "title": "IDOR 漏洞详解与防护实践",
    "date": "2026-05-13",
    "summary": "系统梳理IDOR的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "IDOR",
      "访问控制",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-teal",
    "readingTime": "14 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-JSON-injection-JSON注入详解与防护",
    "sourcePath": "../content/posts/安全研究/JSON injection/JSON注入详解与防护.md",
    "category": "安全研究",
    "title": "JSON 注入详解与防护实践",
    "date": "2026-05-12",
    "summary": "系统梳理JSON 注入的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "JSON注入",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-blue",
    "readingTime": "13 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-LFI-本地文件包含LFI详解与防护",
    "sourcePath": "../content/posts/安全研究/LFI/本地文件包含LFI详解与防护.md",
    "category": "安全研究",
    "title": "本地文件包含 LFI 详解与防护实践",
    "date": "2026-05-11",
    "summary": "系统梳理LFI的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "文件包含",
      "LFI",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-yellow",
    "readingTime": "15 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-NoSQL-injection-NoSQL注入详解与防护",
    "sourcePath": "../content/posts/安全研究/NoSQL injection/NoSQL注入详解与防护.md",
    "category": "安全研究",
    "title": "NoSQL 注入详解与防护实践",
    "date": "2026-05-10",
    "summary": "系统梳理NoSQL 注入的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "NoSQL注入",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-green",
    "readingTime": "14 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-OScmd-操作系统命令注入详解与防护",
    "sourcePath": "../content/posts/安全研究/OScmd/操作系统命令注入详解与防护.md",
    "category": "安全研究",
    "title": "操作系统命令注入详解与防护实践",
    "date": "2026-05-09",
    "summary": "系统梳理操作系统命令注入的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "命令注入",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-orange",
    "readingTime": "16 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-RCE-远程代码执行RCE详解与防护",
    "sourcePath": "../content/posts/安全研究/RCE/远程代码执行RCE详解与防护.md",
    "category": "安全研究",
    "title": "远程代码执行 RCE 详解与防护实践",
    "date": "2026-05-08",
    "summary": "系统梳理RCE的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "RCE",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-pink",
    "readingTime": "16 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-RFI-远程文件包含RFI详解与防护",
    "sourcePath": "../content/posts/安全研究/RFI/远程文件包含RFI详解与防护.md",
    "category": "安全研究",
    "title": "远程文件包含 RFI 详解与防护实践",
    "date": "2026-05-07",
    "summary": "系统梳理RFI的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "文件包含",
      "RFI",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-teal",
    "readingTime": "14 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-SQLi-SQL注入详解与防护",
    "sourcePath": "../content/posts/安全研究/SQLi/SQL注入详解与防护.md",
    "category": "安全研究",
    "title": "SQL 注入详解与防护实践",
    "date": "2026-05-06",
    "summary": "系统梳理SQL 注入的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "SQL注入",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-blue",
    "readingTime": "22 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-SSRF-SSRF详细介绍与防护",
    "sourcePath": "../content/posts/安全研究/SSRF/SSRF详细介绍与防护.md",
    "category": "安全研究",
    "title": "SSRF 漏洞详解与防护实践",
    "date": "2026-05-02",
    "summary": "系统梳理 SSRF 的成因、常见攻击面、危害、测试思路和工程防护方案，重点说明如何在 URL 校验、网络出口、云元数据、重定向、DNS 解析和日志监控层面降低风险。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "SSRF",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-yellow",
    "readingTime": "24 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-XSS-XSS跨站脚本详解与防护",
    "sourcePath": "../content/posts/安全研究/XSS/XSS跨站脚本详解与防护.md",
    "category": "安全研究",
    "title": "XSS 跨站脚本详解与防护实践",
    "date": "2026-05-01",
    "summary": "系统梳理XSS的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "XSS",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-green",
    "readingTime": "24 分钟",
    "featured": false
  },
  {
    "slug": "安全研究-XXE-XXE漏洞详解与防护",
    "sourcePath": "../content/posts/安全研究/XXE/XXE漏洞详解与防护.md",
    "category": "安全研究",
    "title": "XXE 漏洞详解与防护实践",
    "date": "2026-04-25",
    "summary": "系统梳理XXE的漏洞原理、常见攻击方式、风险影响、测试关注点和工程防护手段。",
    "tags": [
      "安全研究",
      "漏洞库",
      "Web安全",
      "XXE",
      "安全防护",
      "安全测试"
    ],
    "cover": "app-orange",
    "readingTime": "18 分钟",
    "featured": false
  }
];
