import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const inputPath = join(root, 'node_modules', 'animal-island-ui', 'dist', 'index.css');
const outputPath = join(root, 'src', 'vendor', 'animal-island-ui.css');

const css = readFileSync(inputPath, 'utf8')
  .replace(/@font-face\s*\{[^{}]*\}/g, '')
  .replace(/Nunito,\s*"Noto Sans SC",\s*"Zen Maru Gothic",\s*/g, '')
  .replace(/Nunito,\s*Noto Sans SC,\s*Zen Maru Gothic,\s*/g, '')
  .replace(/url\((['"]?)\.\/files\//g, 'url($1../../node_modules/animal-island-ui/dist/files/');

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `/* Auto-generated by scripts/prepare-ui-css.mjs. Do not edit by hand. */\n${css}`,
);
